kind: pipeline
type: docker
name: Run tests

steps:
  - name: Run all tests
    image: node
    commands:
      - npm install
      - npm test

trigger:
  event:
  - tag

---
kind: pipeline
type: docker
name: Build documentation

steps:
  - name: Build documentation
    image: node
    commands:
      - git clone https://jsbox.xyz/InvidJS/docs ../docs
      - npm install
      - npm run docs:build
      - cd ../docs
      - git config user.email ci-bot@jsbox.xyz
      - git config user.name ci-bot
      - git add -A
      - git commit -a -m "CI - Rebuild docs"
      - git push

trigger:
  event:
  - tag

---
kind: pipeline
type: docker
name: Publish to NPM

steps:
  - name: Publish
    image: node
    commands:
      - npm install
      - npm run build
      - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - cd dist && npm publish --access public
    environment:
      NPM_TOKEN:
        from_secret: npm_token
        
trigger:
  event:
  - tag
