version: 36
jobs:
- name: Run tests
  steps:
  - !CheckoutStep
    name: Clone repository
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run tests
    runInContainer: true
    image: node:lts-bookworm-slim
    interpreter: !DefaultInterpreter
      commands: |
        npm install
        npm test
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: '"Log" contains "Command exited with code 1"'
  maxRetries: 10
  retryDelay: 30
  timeout: 3600
- name: Build documentation
  steps:
  - !CheckoutStep
    name: Clone repository
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build docs
    runInContainer: true
    image: node:lts-bookworm-slim
    interpreter: !DefaultInterpreter
      commands: |
        apt update && apt install git -y
        git clone https://ci-bot:@secret:ci_password@@@jsbox.xyz/InvidJS/docs ../docs
        npm install
        npm run docs:build
        cd ../docs
        git config user.email ci-bot@@jsbox.xyz
        git config user.name ci-bot
        git add -A
        git commit -a -m "CI - Rebuild docs"
        git push
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Publish
  steps:
  - !CheckoutStep
    name: Clone repository
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Publish to NPM
    runInContainer: true
    image: node:lts-bookworm-slim
    interpreter: !DefaultInterpreter
      commands: |
        npm run build
        npm config set //registry.npmjs.org/:_authToken=@secret:npm_token@
        cd dist && npm publish --access public
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: GitHub Sync
  steps:
  - !PushRepository
    name: Sync
    remoteUrl: https://github.com/InvidJS/InvidJS.git
    userName: alexavil
    passwordSecret: github_token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
