steps:
  - name: Run all tests
    image: node
    commands:
      - npm install
      - npm test
    when:
      - event: push
  - name: Build documentation
    image: node
    commands:
      - git clone https://jsbox.xyz/InvidJS/docs ../docs
      - npm install
      - npm run docs:build
      - cd ../docs
      - git config user.email ci-bot@jsbox.xyz
      - git config user.name ci-bot
      - git add -A
      - git commit -a -m "CI - Rebuild docs"
      - git push
    when:
      - event: tag      
  - name: Publish
    image: node
    commands:
      - npm run build
      - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - cd dist && npm publish --access public
    secrets: [ npm_token ]
    when:
      - event: tag 

