name: Request a feature
description: Suggest an idea for InvidJS.
title: "[Feature Request]"
labels: ["enhancement"]
body: 
  - type: markdown
    attributes:
      value: |
        Please take your time to fill the form carefully.
  - type: textarea
    id: request
    attributes:
      label: Please describe your request.
      description: A clear and concise description of what you want to be added.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.      