name: CI - Build docs (bleeding-edge)

on:
  push:
    branches:
      - bleeding-edge
    paths:
      - "index.ts"
      - "jest.config.js"
      - "api/**"
      - "tests/**"
      - "utils/**"
  workflow_dispatch:

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Clone code
        uses: actions/checkout@v3
        with:
          path: "./code"
      - name: Clone docs
        uses: actions/checkout@v3
        with:
          repository: "InvidJS/docs-bleeding-edge"
          path: "./docs"
          token: ${{secrets.GH_TOKEN}}
      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          cd code
          npm install
      - name: Build docs
        run: |
          cd code
          npm run docs:build
          cd ../docs
          git config user.email actions@github.com
          git config user.name GitHub Actions
          git add -A
          git commit -a -m "CI: Rebuild docs (bleeding-edge)"
          git push
