name: CI - Run tests

on:
  pull_request:
    branches:
      - master
      - bleeding-edge
  push:
    branches:
      - master
      - bleeding-edge
    paths:
      - "index.ts"
      - "jest.config.js"
      - "api/**"
      - "tests/**"
      - "utils/**"
  workflow_dispatch:

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
